### ISSUE TITLE
I can't see the emojis like you show in your book (page 144)

### ISSUE THREAD

**Issue by andreshg112** [christophrumpel/bcwp-laraconeu-chatbot#2]
Formatted message:
![image](https://user-images.githubusercontent.com/15859884/44306091-2ac28300-a34d-11e8-8f66-f2d73ab136ef.png)

Code:
![image](https://user-images.githubusercontent.com/15859884/44306093-301fcd80-a34d-11e8-9dfb-9f3218ea3b57.png)

Your book:
![image](https://user-images.githubusercontent.com/15859884/44306097-3f068000-a34d-11e8-888f-4160e0da8afd.png)

**Comment by christophrumpel** [comment]
Hey,
which version of book do you have? I removed the emojis in the last version of the book, because there are problems with the ebook formats from the markdown files I had while writing.

**Comment by andreshg112** [comment]
buildchatbotswithphp_v1.1.pdf

**Comment by christophrumpel** [comment]
Hey, ok I see there is still the wrong characters in there. Please change `â‚¬29` to `➡️ €...`. Or leave it out. But you also need to make sure to have it the same in the tests. I try to change it in the book as soon as possible. Thanks for mentioning.

**Comment by andreshg112** [comment]
What's the character for the plane and train?

**Comment by andreshg112** [comment]
I used these: ✈, 🚆

**Comment by christophrumpel** [comment]
yeah of course. Basically you can use the emojis you prefer 👍
